{% set name = "fastcore" %}
{% set version = "1.12.11" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e301add06f8b1240b5484197b221eeac00c77daf25c67ddd559020527f2a6d7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - py2pyi = fastcore.py2pyi:py2pyi
    - replace_wildcards = fastcore.py2pyi:replace_wildcards
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - setuptools >=64
  run:
    - python

test:
  imports:
    - fastcore
  commands:
    - pip check
    - py2pyi --help
    - replace_wildcards --help
  requires:
    - pip

about:
  home: https://fastcore.fast.ai
  summary: Python supercharged for fastai development
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Python is a powerful, dynamic language. Rather than bake everything into
    the language, it lets the programmer customize it to make it work for them.
    fastcore uses this flexibility to add to Python features inspired by other
    languages we've loved, like multiple dispatch from Julia, mixins from Ruby,
    and currying, binding, and more from Haskell. It also adds some
    “missing features” and clean up some rough edges in the Python standard
    library, such as simplifying parallel processing, and bringing ideas
    from NumPy over to Python's list type.
  dev_url: https://github.com/fastai/fastcore
  doc_url: https://fastcore.fast.ai/tour.html

extra:
  recipe-maintainers:
    - kai-tub