{% set name = "fastcore" %}
{% set version = "1.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastcore-{{ version }}.tar.gz
  sha256: b7ae674a713c55b0563da253a1c3aaa2acc8c5611dd0141b49fdb057d42cfa4d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - packaging
    - pip
    - python >=3.6

test:
  imports:
    - fastcore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastai/fastcore/tree/master/
  summary: Python supercharged for fastai development
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kai-tub
