{% set name = "fastcore" %}
{% set version = "1.7.20" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastcore-{{ version }}.tar.gz
  sha256: 316dcb0e2d5e338e069f338b3c136ca9eb4ce950ca433da2a80952fc5928ddab

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - py2pyi=fastcore.py2pyi:py2pyi

requirements:
  host:
    - pip
    - python
    - setuptools >=64.0
    - wheel
  run:
    - python
    - packaging

test:
  imports:
    - fastcore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://fastcore.fast.ai/
  dev_url: https://github.com/fastai/fastcore
  doc_url: https://fastcore.fast.ai/tour.html
  summary: Python supercharged for fastai development
  description: |
    Python is a powerful, dynamic language. Rather than bake everything into 
    the language, it lets the programmer customize it to make it work for them. 
    fastcore uses this flexibility to add to Python features inspired by other 
    languages we've loved, like multiple dispatch from Julia, mixins from Ruby, 
    and currying, binding, and more from Haskell. It also adds some 
    “missing features” and clean up some rough edges in the Python standard 
    library, such as simplifying parallel processing, and bringing ideas 
    from NumPy over to Python's list type.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - kai-tub
