{% set name = "fastcore" %}
{% set version = "1.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastcore-{{ version }}.tar.gz
  sha256: 737effc54a6ed1189e0ea514342def4d9693c0d219f3a49d1ef44f616890ff2d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - packaging
    - pip
    - python >=3.6

test:
  imports:
    - fastcore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastai/fastcore/tree/master/
  summary: Python supercharged for fastai development
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kai-tub
